/**
 * Emits a cross-language licence fixture for packages/secure-core to verify against.
 *
 *   npx tsx tools/emit-license-fixture.ts
 *
 * The server signs licences here in Node; the device verifies them in Rust, offline. A field name or
 * CBOR encoding difference between the two would produce licences that every device rejects — and
 * the student-visible symptom is "expired", which points nowhere near the real cause.
 *
 * The fixture is committed at packages/secure-core/tests/fixtures/license-vector.json and checked by
 * `cargo test --test wire_compat`. Regenerate only when the licence format changes deliberately.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import {
  publicKeyRaw,
  signLicense,
  type LicensePayloadWire,
} from '../src/modules/licensing/license.signer.js';

// A fixed seed, so the fixture is reproducible and reviewable in a diff.
const PRIVATE_KEY_RAW = Buffer.from(
  '1122334455667788990011223344556677889900112233445566778899001122',
  'hex',
);

const payload: LicensePayloadWire = {
  v: 1,
  license_id: 'lic_01J8ZQK5T9XVWR3M2N4P6H8B7C',
  user_id: 'usr_01J8ZQK5T9XVWR3M2N4P6H8B7C',
  device_ids: ['dev_01J8ZQK5T9XVWR3M2N4P6H8B7C'],
  course_ids: ['crs_01J8ZQK5T9XVWR3M2N4P6H8B7C'],
  video_ids: [],
  not_before: '2026-09-01T00:00:00.000Z',
  not_after: '2026-10-01T00:00:00.000Z',
  max_devices: 2,
  max_concurrent_streams: 1,
  offline_window_days: 30,
  revocation_epoch: 3,
  issued_at: '2026-09-01T00:00:00.000Z',
  server_time: '2026-09-01T00:00:00.000Z',
};

const privateBase64 = PRIVATE_KEY_RAW.toString('base64');
const signed = signLicense(payload, privateBase64);

// Derive the public half from the private key, the same way the API does at boot.
import { createPrivateKey, createPublicKey } from 'node:crypto';
const privateKey = createPrivateKey({
  key: Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), PRIVATE_KEY_RAW]),
  format: 'der',
  type: 'pkcs8',
});
const publicDer = createPublicKey(privateKey).export({ format: 'der', type: 'spki' });
const publicRaw = publicKeyRaw(publicDer.toString('base64'));

const fixture = {
  _comment:
    'Generated by services/api/tools/emit-license-fixture.ts. A Node-signed licence, verified by ' +
    'packages/secure-core in Rust. If the Rust test fails against this file, the two licence ' +
    'implementations have diverged — fix the code, do not regenerate the fixture.',
  publicKey: publicRaw.toString('base64'),
  payload,
  signedBlob: signed.signedBytes.toString('base64'),
  signature: signed.signature.toString('base64'),
};

const out = join(
  import.meta.dirname ?? __dirname,
  '../../../packages/secure-core/tests/fixtures/license-vector.json',
);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify(fixture, null, 2)}\n`);

console.log(`wrote ${out}`);
console.log(`  public key  ${fixture.publicKey}`);
console.log(`  signature   ${fixture.signature.slice(0, 32)}…`);
