import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { describe, expect, it } from 'vitest';

import {
  generateContentKey,
  segmentIv,
  unwrapKeyForDevice,
  wrapKeyForDevice,
  x25519PublicKeyFromRaw,
} from './key-wrap.js';

const SPKI_PREFIX_LEN = 12;
const PKCS8_PREFIX_LEN = 16;

function deviceKeypair() {
  const { publicKey, privateKey } = generateKeyPairSync('x25519');
  return {
    publicRaw: publicKey.export({ format: 'der', type: 'spki' }).subarray(SPKI_PREFIX_LEN),
    privateRaw: privateKey.export({ format: 'der', type: 'pkcs8' }).subarray(PKCS8_PREFIX_LEN),
  };
}

describe('wrapKeyForDevice', () => {
  const deviceId = 'dev_01J8ZQK5T9XVWR3M2N4P6H8B7C';

  it('round trips for the intended device', () => {
    const { publicRaw, privateRaw } = deviceKeypair();
    const cek = generateContentKey();

    const wrapped = wrapKeyForDevice(cek, Buffer.from(publicRaw), deviceId);

    expect(unwrapKeyForDevice(wrapped, Buffer.from(privateRaw), deviceId)).toEqual(cek);
  });

  it('cannot be opened by a different device', () => {
    // The property that makes a copied .tihex file worthless.
    const owner = deviceKeypair();
    const thief = deviceKeypair();
    const cek = generateContentKey();

    const wrapped = wrapKeyForDevice(cek, Buffer.from(owner.publicRaw), deviceId);

    expect(() => unwrapKeyForDevice(wrapped, Buffer.from(thief.privateRaw), deviceId)).toThrow();
  });

  it('cannot be replayed under a different device id', () => {
    // The device id is AAD, so a wrap lifted from one manifest into another fails even on the
    // correct hardware.
    const { publicRaw, privateRaw } = deviceKeypair();
    const cek = generateContentKey();

    const wrapped = wrapKeyForDevice(cek, Buffer.from(publicRaw), deviceId);

    expect(() =>
      unwrapKeyForDevice(wrapped, Buffer.from(privateRaw), 'dev_01KFORGEDAAAAAAAAAAAAAAAA'),
    ).toThrow();
  });

  it('rejects tampered ciphertext', () => {
    const { publicRaw, privateRaw } = deviceKeypair();
    const wrapped = wrapKeyForDevice(generateContentKey(), Buffer.from(publicRaw), deviceId);

    wrapped[wrapped.length - 1] ^= 0xff;

    expect(() => unwrapKeyForDevice(wrapped, Buffer.from(privateRaw), deviceId)).toThrow();
  });

  it('produces a different wrap every time for the same key', () => {
    // Ephemeral keys must not be reused: two identical wraps would mean a reused derived key.
    const { publicRaw } = deviceKeypair();
    const cek = generateContentKey();

    const a = wrapKeyForDevice(cek, Buffer.from(publicRaw), deviceId);
    const b = wrapKeyForDevice(cek, Buffer.from(publicRaw), deviceId);

    expect(a.equals(b)).toBe(false);
  });

  it('refuses a content key of the wrong length', () => {
    const { publicRaw } = deviceKeypair();
    expect(() => wrapKeyForDevice(randomBytes(32), Buffer.from(publicRaw), deviceId)).toThrow(
      /16 bytes/,
    );
  });

  it('refuses a malformed device public key', () => {
    expect(() => x25519PublicKeyFromRaw(randomBytes(31))).toThrow(/32 bytes/);
  });
});

describe('segmentIv', () => {
  it('is deterministic', () => {
    expect(segmentIv('ck_test', 42)).toEqual(segmentIv('ck_test', 42));
  });

  it('differs per sequence number', () => {
    // AES-CTR IV reuse leaks the XOR of two segments, so this is load-bearing.
    expect(segmentIv('ck_test', 1).equals(segmentIv('ck_test', 2))).toBe(false);
  });

  it('differs per video', () => {
    expect(segmentIv('ck_one', 1).equals(segmentIv('ck_two', 1))).toBe(false);
  });

  it('is 16 bytes', () => {
    expect(segmentIv('ck_test', 0)).toHaveLength(16);
  });
});

/**
 * Cross-language wire compatibility.
 *
 * The server wraps keys in Node; the device unwraps them in Rust. Nothing in either test suite
 * alone would notice if the two derivations drifted apart — the symptom would be downloads that
 * no device can open, discovered in the field.
 *
 * The fixture is generated by `packages/secure-core` (`cargo test --test wire_compat -- --ignored
 * --nocapture` writes it) and committed. If this test fails, the two implementations have
 * diverged and one of them is wrong; do not regenerate the fixture to make it pass.
 */
describe('wire compatibility with secure-core (Rust)', () => {
  const fixturePath = join(__dirname, '__fixtures__', 'wire-vectors.json');

  it('derives the same segment IVs as the Rust implementation', () => {
    const fixture = JSON.parse(readFileSync(fixturePath, 'utf8'));

    for (const vector of fixture.segmentIvs) {
      expect(
        segmentIv(vector.keyId, vector.sequence).toString('hex'),
        `segment IV mismatch for keyId=${vector.keyId} seq=${vector.sequence}`,
      ).toBe(vector.iv);
    }
  });

  it('unwraps a key that the Rust implementation wrapped', () => {
    const fixture = JSON.parse(readFileSync(fixturePath, 'utf8'));
    const { wrappedKey, devicePrivateKey, deviceId, contentKey } = fixture.keyWrap;

    const unwrapped = unwrapKeyForDevice(
      Buffer.from(wrappedKey, 'base64'),
      Buffer.from(devicePrivateKey, 'base64'),
      deviceId,
    );

    expect(unwrapped.toString('base64')).toBe(contentKey);
  });
});
