import { PrismaClient } from '@prisma/client';
import { afterAll, describe, expect, it } from 'vitest';

import { normalizeFa } from './search.js';

/**
 * Asserts that `normalize_fa()` in SQL and `normalizeFa()` in TypeScript agree.
 *
 * This pairing is a silent-failure waiting to happen. The `search_text` columns are generated by the
 * SQL function; queries are normalised by the TypeScript one. If they drift, nothing throws — every
 * search just returns nothing, and the cause is not visible from either side alone.
 *
 * Skipped when no database is reachable, so `pnpm test` still works without Docker. CI provides
 * Postgres, so it runs there.
 */
const hasDatabase = Boolean(process.env.DATABASE_URL);
const prisma = hasDatabase ? new PrismaClient() : null;

const CASES = [
  // Arabic vs Persian letter forms — visually identical, different code points.
  'كتاب',
  'عربي',
  'حتى',
  'آب',
  'أحمد',
  // Zero-width non-joiner inside compound words.
  'می‌شود',
  'نمی‌توانم',
  // Diacritics, usually omitted when typing.
  'مُشتَق',
  'کِتاب',
  // Tatweel (decorative letter stretching).
  'ریاضـــیات',
  // Digit forms.
  'نیمسال ۱۴۰۵',
  'جلسه ٤',
  '۱۲۳ و 456',
  // Whitespace and mixed scripts.
  '  جلسه   چهارم  ',
  'Calculus مشتق',
  // Already-normal text must pass through unchanged.
  'مشتق توابع مرکب',
  'حد و پیوستگی',
  // Edge cases.
  '',
  '   ',
];

describe.skipIf(!hasDatabase)('normalize_fa parity between SQL and TypeScript', () => {
  afterAll(async () => {
    await prisma?.$disconnect();
  });

  it('produces identical output for every case', async () => {
    const rows = await prisma!.$queryRaw<Array<{ input: string; sql: string }>>`
      SELECT t.input, normalize_fa(t.input) AS sql
      FROM unnest(${CASES}::text[]) AS t(input)
    `;

    const mismatches = rows
      .map((row) => ({ ...row, ts: normalizeFa(row.input) }))
      .filter((row) => row.sql !== row.ts);

    expect(
      mismatches,
      `SQL and TypeScript normalisation disagree — searches will silently return nothing:\n${mismatches
        .map(
          (m) =>
            `  ${JSON.stringify(m.input)}: sql=${JSON.stringify(m.sql)} ts=${JSON.stringify(m.ts)}`,
        )
        .join('\n')}`,
    ).toEqual([]);
  });

  it('matches a query against a generated search_text column', async () => {
    // End-to-end proof: text stored one way is found by a query normalised the other way.
    const [row] = await prisma!.$queryRaw<Array<{ matched: boolean }>>`
      SELECT normalize_fa('كتاب مُشتَق ۱۴۰۵') = ${normalizeFa('کتاب مشتق 1405')} AS matched
    `;

    expect(row?.matched).toBe(true);
  });
});
