/**
 * Persian text normalisation for search.
 *
 * PostgreSQL has no Persian stemmer, and Persian text has several traps that make a naive `LIKE`
 * miss obvious matches:
 *
 *   * Arabic vs Persian letter forms — a student types Arabic kaf, the database holds Persian
 *     keheh. Visually identical, different code points.
 *   * The zero-width non-joiner inside compound words.
 *   * Optional diacritics (harakat), usually omitted but sometimes present.
 *   * Arabic-Indic and Persian digits alongside Western ones.
 *
 * The same transformation must exist in SQL (`normalize_fa`, in the initial migration) and here, and
 * the two must agree: the `search_text` columns are generated by the SQL version, and queries are
 * normalised by this one. If they diverge, searches silently return nothing — there is no error.
 * `search.integration.test.ts` asserts the two agree, and runs in CI.
 *
 * ## Why code points instead of literal characters
 *
 * Every character below is named by its numeric code point, and the regexes are built at module load
 * rather than written as literals. Two reasons, both learned the hard way:
 *
 *   * A literal ZWNJ or bidi mark in source is **invisible in a diff**. Nobody can review it, and a
 *     stray one survives for years. ESLint's `no-irregular-whitespace` rejects them outright.
 *   * The characters involved are visually identical to their replacements — Arabic kaf and Persian
 *     keheh look the same in every editor — so a literal-character version of this file is
 *     unreadable even to someone who reads Persian.
 *
 * Do not "simplify" this back to literal characters or `\u` escapes.
 */

const ARABIC_KAF = 0x0643;
const PERSIAN_KEHEH = 0x06a9;

const ARABIC_YEH = 0x064a;
const ARABIC_ALEF_MAKSURA = 0x0649;
const PERSIAN_YEH = 0x06cc;

const ALEF_MADDA = 0x0622;
const ALEF_HAMZA_ABOVE = 0x0623;
const ALEF_HAMZA_BELOW = 0x0625;
const PLAIN_ALEF = 0x0627;

const HEH_YEH = 0x06c0;
const HEH_GOAL_HAMZA = 0x06c2;
const HEH_GOAL = 0x06c3;
const PLAIN_HEH = 0x0647;

/** Decorative letter stretching. */
const TATWEEL = 0x0640;

const PERSIAN_ZERO = 0x06f0;
const PERSIAN_NINE = 0x06f9;
const ARABIC_INDIC_ZERO = 0x0660;
const ARABIC_INDIC_NINE = 0x0669;

const chr = String.fromCharCode;

/**
 * Builds a global character-class regex from code points and ranges.
 *
 * Safe to interpolate directly: none of the code points used here are regex metacharacters, and all
 * are well above the ASCII range where `-`, `]` and `\` live.
 */
function charClass(...parts: Array<number | [number, number]>): RegExp {
  const body = parts
    .map((part) => (Array.isArray(part) ? `${chr(part[0])}-${chr(part[1])}` : chr(part)))
    .join('');
  return new RegExp(`[${body}]`, 'g');
}

const KAF_PATTERN = charClass(ARABIC_KAF);
const YEH_PATTERN = charClass(ARABIC_YEH, ARABIC_ALEF_MAKSURA);
const ALEF_PATTERN = charClass(ALEF_MADDA, ALEF_HAMZA_ABOVE, ALEF_HAMZA_BELOW);
const HEH_PATTERN = charClass(HEH_YEH, HEH_GOAL_HAMZA, HEH_GOAL);
const TATWEEL_PATTERN = charClass(TATWEEL);

/** Zero-width and bidi formatting characters, including the ZWNJ inside compound words. */
const FORMATTING_PATTERN = charClass(
  [0x200b, 0x200f], // zero-width space through right-to-left mark
  [0x202a, 0x202e], // bidi embedding and override controls
  0xfeff, // byte-order mark
);

/** Harakat and other combining marks, usually omitted when typing. */
const DIACRITICS_PATTERN = charClass(
  [0x064b, 0x065f], // fathatan through wavy hamza below
  0x0670, // superscript alef
  [0x06d6, 0x06ed], // Quranic annotation marks
);

const PERSIAN_DIGITS_PATTERN = charClass([PERSIAN_ZERO, PERSIAN_NINE]);
const ARABIC_INDIC_DIGITS_PATTERN = charClass([ARABIC_INDIC_ZERO, ARABIC_INDIC_NINE]);

export function normalizeFa(input: string): string {
  return input
    .normalize('NFKC')
    .replace(KAF_PATTERN, chr(PERSIAN_KEHEH))
    .replace(YEH_PATTERN, chr(PERSIAN_YEH))
    .replace(ALEF_PATTERN, chr(PLAIN_ALEF))
    .replace(HEH_PATTERN, chr(PLAIN_HEH))
    .replace(TATWEEL_PATTERN, '')
    .replace(DIACRITICS_PATTERN, '')
    .replace(FORMATTING_PATTERN, '')
    .replace(PERSIAN_DIGITS_PATTERN, (d) => String(d.charCodeAt(0) - PERSIAN_ZERO))
    .replace(ARABIC_INDIC_DIGITS_PATTERN, (d) => String(d.charCodeAt(0) - ARABIC_INDIC_ZERO))
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

/**
 * Prepares a user's query for trigram matching.
 *
 * Queries shorter than two characters are rejected by the schema: a one-character trigram search
 * matches most of the catalogue, slowly, for a useless result.
 */
export function prepareSearchQuery(raw: string): string {
  return normalizeFa(raw).slice(0, 120);
}
