/**
 * Emits a cross-language segment fixture for packages/secure-core to decrypt.
 *
 *   pnpm --filter @tihe/media-worker emit-fixtures
 *
 * The packager encrypts segments in Node; the device decrypts them in Rust. Nothing in either test
 * suite alone would notice if the AES mode or the IV derivation drifted apart — the symptom is a
 * black screen in the player, with no error on either side.
 *
 * Kept deliberately tiny (a two-second clip) so the committed fixture stays reviewable.
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { segmentIv } from '@tihe/crypto';
import { createCipheriv } from 'node:crypto';

import { SEGMENT_SECONDS } from '../src/ffmpeg.js';

// Fixed so the fixture is reproducible and a diff shows only real changes.
const CONTENT_KEY = Buffer.from('a0a1a2a3a4a5a6a7a8a9aaabacadaeaf', 'hex');
const CONTENT_KEY_ID = 'ck_01J8ZQK5T9XVWR3M2N4P6H8B7C';

const work = mkdtempSync(join(tmpdir(), 'seg-fixture-'));

try {
  const source = join(work, 'source.mp4');
  const encode = spawnSync('ffmpeg', [
    '-hide_banner',
    '-loglevel',
    'error',
    '-y',
    '-f',
    'lavfi',
    '-i',
    'testsrc=size=320x240:rate=25:duration=2',
    '-c:v',
    'libx264',
    '-preset',
    'ultrafast',
    '-pix_fmt',
    'yuv420p',
    source,
  ]);
  if (encode.status !== 0) {
    throw new Error(`ffmpeg failed: ${encode.stderr?.toString().slice(-400)}`);
  }

  const hlsDir = join(work, 'hls');
  mkdirSync(hlsDir, { recursive: true });
  const pack = spawnSync('ffmpeg', [
    '-hide_banner',
    '-loglevel',
    'error',
    '-y',
    '-i',
    source,
    '-c',
    'copy',
    '-f',
    'hls',
    '-hls_time',
    String(SEGMENT_SECONDS),
    '-hls_list_size',
    '0',
    '-hls_playlist_type',
    'vod',
    '-hls_segment_type',
    'mpegts',
    '-hls_segment_filename',
    join(hlsDir, 'seg-%05d.ts'),
    join(hlsDir, 'index.m3u8'),
  ]);
  if (pack.status !== 0) {
    throw new Error(`ffmpeg HLS failed: ${pack.stderr?.toString().slice(-400)}`);
  }

  const segments = readdirSync(hlsDir)
    .filter((f) => f.endsWith('.ts'))
    .sort();
  const plaintext = readFileSync(join(hlsDir, segments[0]!));

  const iv = segmentIv(CONTENT_KEY_ID, 0);
  const cipher = createCipheriv('aes-128-ctr', CONTENT_KEY, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]);

  const fixture = {
    _comment:
      'Generated by services/media-worker/tools/emit-segment-fixture.ts. A segment encrypted by the ' +
      'Node packager, decrypted by packages/secure-core in Rust. If the Rust test fails against this ' +
      'file, the two implementations have diverged — fix the code, do not regenerate the fixture.',
    contentKeyId: CONTENT_KEY_ID,
    contentKey: CONTENT_KEY.toString('base64'),
    sequence: 0,
    iv: iv.toString('hex'),
    plaintextLength: plaintext.length,
    encryptedSegment: ciphertext.toString('base64'),
  };

  const out = join(
    import.meta.dirname ?? __dirname,
    '../../../packages/secure-core/tests/fixtures/segment-vector.json',
  );
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, `${JSON.stringify(fixture, null, 2)}\n`);

  console.log(`wrote ${out}`);
  console.log(`  key id     ${CONTENT_KEY_ID}`);
  console.log(`  iv         ${fixture.iv}`);
  console.log(`  plaintext  ${plaintext.length} bytes (${plaintext.length / 188} TS packets)`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
