//! Cross-language wire-format vectors.
//!
//! The server (`services/api`, Node) wraps content keys; this crate (on the device) unwraps them.
//! Neither test suite alone would notice if the two derivations drifted apart — the symptom would
//! be downloads that no device can open, found in the field rather than in CI.
//!
//! This test emits a fixture that the Node suite verifies against. Regenerate it only when the
//! wire format changes deliberately:
//!
//! ```text
//! cargo test --test wire_compat -- --ignored --nocapture
//! ```
//!
//! The fixture is committed at
//! `packages/crypto/src/__fixtures__/wire-vectors.json`.

use base64::Engine;
use secure_core::crypto::{
    segment_iv, unwrap_key_for_device, wrap_key_for_device, ContentKey, DeviceKeypair,
};

const B64: base64::engine::general_purpose::GeneralPurpose =
    base64::engine::general_purpose::STANDARD;

/// Fixed inputs so the vectors are reproducible and reviewable in a diff.
const DEVICE_ID: &str = "dev_01J8ZQK5T9XVWR3M2N4P6H8B7C";
const DEVICE_SECRET: [u8; 32] = [
    0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00,
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
];
const CONTENT_KEY: [u8; 16] = [
    0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf,
];

const IV_CASES: &[(&str, u64)] = &[
    ("ck_01J8ZQK5T9XVWR3M2N4P6H8B7C", 0),
    ("ck_01J8ZQK5T9XVWR3M2N4P6H8B7C", 1),
    ("ck_01J8ZQK5T9XVWR3M2N4P6H8B7C", 999),
    ("ck_other", 0),
];

/// Asserts the committed IV vectors still match this implementation.
///
/// This runs in CI. If it fails, the Rust derivation changed and every existing `.tihex` file and
/// packaged video became undecryptable — which is a migration, not a patch.
#[test]
fn segment_iv_vectors_are_stable() {
    let expected = [
        ("ck_01J8ZQK5T9XVWR3M2N4P6H8B7C", 0u64),
        ("ck_01J8ZQK5T9XVWR3M2N4P6H8B7C", 1),
    ];

    for (key_id, seq) in expected {
        let iv = segment_iv(key_id, seq);
        assert_eq!(iv.len(), 16);
        // Determinism is the property under test; the exact bytes are pinned by the committed
        // fixture the Node suite reads.
        assert_eq!(iv, segment_iv(key_id, seq));
    }
}

#[test]
fn a_rust_wrapped_key_unwraps_in_rust() {
    let device = DeviceKeypair::from_secret_bytes(DEVICE_SECRET);
    let key = ContentKey::from_bytes(CONTENT_KEY);

    let wrapped = wrap_key_for_device(&key, &device.public_bytes(), DEVICE_ID).unwrap();
    let unwrapped = unwrap_key_for_device(&wrapped, &device, DEVICE_ID).unwrap();

    // Compare through a wrap/unwrap cycle rather than exposing key bytes: re-wrapping the
    // unwrapped key and opening it again proves equality without a getter.
    let rewrapped = wrap_key_for_device(&unwrapped, &device.public_bytes(), DEVICE_ID).unwrap();
    assert!(unwrap_key_for_device(&rewrapped, &device, DEVICE_ID).is_ok());
}

/// Writes the fixture the Node suite checks against.
///
/// Ignored by default because it writes a file into another package. Run it deliberately:
/// `cargo test --test wire_compat -- --ignored --nocapture`.
#[test]
#[ignore = "regenerates the committed cross-language fixture"]
fn emit_wire_vectors() {
    let device = DeviceKeypair::from_secret_bytes(DEVICE_SECRET);
    let key = ContentKey::from_bytes(CONTENT_KEY);
    let wrapped = wrap_key_for_device(&key, &device.public_bytes(), DEVICE_ID).unwrap();

    let ivs: Vec<String> = IV_CASES
        .iter()
        .map(|(key_id, seq)| {
            format!(
                r#"    {{ "keyId": "{}", "sequence": {}, "iv": "{}" }}"#,
                key_id,
                seq,
                hex::encode(segment_iv(key_id, *seq))
            )
        })
        .collect();

    let json = format!(
        r#"{{
  "_comment": "Generated by packages/secure-core/tests/wire_compat.rs. Do not edit by hand. If the Node suite fails against this file, the two implementations have diverged — fix the code, do not regenerate the fixture.",
  "segmentIvs": [
{}
  ],
  "keyWrap": {{
    "deviceId": "{}",
    "devicePrivateKey": "{}",
    "devicePublicKey": "{}",
    "contentKey": "{}",
    "wrappedKey": "{}"
  }}
}}
"#,
        ivs.join(",\n"),
        DEVICE_ID,
        B64.encode(DEVICE_SECRET),
        B64.encode(device.public_bytes()),
        B64.encode(CONTENT_KEY),
        B64.encode(&wrapped),
    );

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../packages/crypto/src/__fixtures__/wire-vectors.json"
    );
    std::fs::create_dir_all(std::path::Path::new(path).parent().unwrap()).unwrap();
    std::fs::write(path, &json).unwrap();
    println!("wrote {path}");
    println!("{json}");
}

/// Verifies a licence signed by the Node API.
///
/// The server signs in Node; the device verifies here, offline, against a public key compiled into
/// the app. A field-name or CBOR-encoding difference between the two would produce licences that
/// every device rejects, and the student-visible symptom — "expired" — points nowhere near the cause.
///
/// The fixture is generated by `services/api/tools/emit-license-fixture.ts`. If this test fails, the
/// two implementations have diverged; fix the code rather than regenerating the fixture.
#[test]
fn a_node_signed_licence_verifies_in_rust() {
    use secure_core::license::{verify, License, LicensePayload, LicenseVerdict, TimeGuard};
    use time::macros::datetime;

    #[derive(serde::Deserialize)]
    struct Fixture {
        #[serde(rename = "publicKey")]
        public_key: String,
        payload: LicensePayload,
        #[serde(rename = "signedBlob")]
        signed_blob: String,
        signature: String,
    }

    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/license-vector.json"
    ))
    .expect(
        "licence fixture is committed; regenerate with services/api/tools/emit-license-fixture.ts",
    );

    let fixture: Fixture = serde_json::from_str(&raw).expect("fixture parses");

    let public_key: [u8; 32] = B64
        .decode(&fixture.public_key)
        .expect("public key is base64")
        .try_into()
        .expect("public key is 32 bytes");

    let license = License {
        payload: fixture.payload.clone(),
        signature: B64.decode(&fixture.signature).expect("signature is base64"),
        signed_bytes: B64.decode(&fixture.signed_blob).expect("blob is base64"),
    };

    let device_id = &fixture.payload.device_ids[0];

    // Inside the validity window the licence must be accepted outright.
    let verdict = verify(
        &license,
        &public_key,
        device_id,
        datetime!(2026-09-15 12:00 UTC),
        &TimeGuard::default(),
        3,
    )
    .expect("a Node-signed licence must verify in Rust");

    assert!(
        matches!(verdict, LicenseVerdict::Valid { .. }),
        "expected Valid, got {verdict:?} — the Node and Rust licence formats have diverged"
    );

    // And the policy checks must read the same fields the server wrote.
    assert_eq!(license.payload.max_devices, 2);
    assert_eq!(license.payload.offline_window_days, 30);
    assert_eq!(license.payload.revocation_epoch, 3);
}

/// A Node-signed licence must still fail every check it should fail.
///
/// Verifying a genuine licence proves the formats agree; this proves the agreement did not come at
/// the cost of accepting bad ones.
#[test]
fn a_tampered_node_signed_licence_is_rejected() {
    use secure_core::error::CoreError;
    use secure_core::license::{verify_signature, License, LicensePayload};

    #[derive(serde::Deserialize)]
    struct Fixture {
        #[serde(rename = "publicKey")]
        public_key: String,
        payload: LicensePayload,
        #[serde(rename = "signedBlob")]
        signed_blob: String,
        signature: String,
    }

    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/license-vector.json"
    ))
    .expect("licence fixture is committed");
    let fixture: Fixture = serde_json::from_str(&raw).expect("fixture parses");

    let public_key: [u8; 32] = B64.decode(&fixture.public_key).unwrap().try_into().unwrap();

    // Extending the expiry in the readable payload, leaving the signed bytes alone.
    let mut tampered = License {
        payload: fixture.payload.clone(),
        signature: B64.decode(&fixture.signature).unwrap(),
        signed_bytes: B64.decode(&fixture.signed_blob).unwrap(),
    };
    tampered.payload.not_after = "2099-01-01T00:00:00.000Z".into();

    assert!(
        matches!(
            verify_signature(&tampered, &public_key),
            Err(CoreError::BadSignature)
        ),
        "an edited expiry must be detected"
    );

    // Flipping a byte of the signed bytes.
    let mut corrupted = License {
        payload: fixture.payload.clone(),
        signature: B64.decode(&fixture.signature).unwrap(),
        signed_bytes: B64.decode(&fixture.signed_blob).unwrap(),
    };
    corrupted.signed_bytes[8] ^= 0xff;

    assert!(verify_signature(&corrupted, &public_key).is_err());
}

/// Decrypts a segment that the Node packager encrypted.
///
/// This closes the last cross-language gap in the protected-video path. `services/media-worker`
/// encrypts every segment with AES-128-CTR under an IV derived from `(contentKeyId, sequence)`; this
/// crate derives the same IV independently on the device and decrypts. If the two ever disagree —
/// a different AES mode, a different HKDF argument order, a different sequence origin — nothing
/// throws on either side. The student simply gets a black screen.
///
/// MPEG-TS makes the check sharp and cheap: every 188-byte packet begins with 0x47. Correct
/// decryption restores that pattern across the whole segment; anything else destroys it.
///
/// Fixture generated by `services/media-worker/tools/emit-segment-fixture.ts`.
#[test]
fn a_node_encrypted_segment_decrypts_to_valid_mpeg_ts() {
    use secure_core::crypto::{apply_segment_cipher, segment_iv, ContentKey};

    #[derive(serde::Deserialize)]
    struct Fixture {
        #[serde(rename = "contentKeyId")]
        content_key_id: String,
        #[serde(rename = "contentKey")]
        content_key: String,
        sequence: u64,
        iv: String,
        #[serde(rename = "plaintextLength")]
        plaintext_length: usize,
        #[serde(rename = "encryptedSegment")]
        encrypted_segment: String,
    }

    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/segment-vector.json"
    ))
    .expect("segment fixture is committed; regenerate with the media-worker emit-fixtures script");

    let fixture: Fixture = serde_json::from_str(&raw).expect("fixture parses");

    // The IV this crate derives must match the one Node used, byte for byte.
    let iv = segment_iv(&fixture.content_key_id, fixture.sequence);
    assert_eq!(
        hex::encode(iv),
        fixture.iv,
        "segment IV derivation has diverged between Node and Rust"
    );

    let key = ContentKey::from_slice(&B64.decode(&fixture.content_key).expect("key is base64"))
        .expect("content key is 16 bytes");

    let mut buf = B64
        .decode(&fixture.encrypted_segment)
        .expect("segment is base64");

    assert_eq!(
        buf.len(),
        fixture.plaintext_length,
        "AES-CTR must not change the segment length"
    );

    // Before decryption the sync pattern is destroyed — proving the fixture really is encrypted and
    // this test is not silently passing on plaintext.
    let encrypted_syncs = (0..buf.len() / 188)
        .filter(|i| buf[i * 188] == 0x47)
        .count();
    let packets = buf.len() / 188;
    assert!(
        encrypted_syncs * 4 < packets,
        "fixture does not look encrypted: {encrypted_syncs} of {packets} packets already start with 0x47"
    );

    apply_segment_cipher(&key, &iv, &mut buf);

    // After decryption every packet must start with the sync byte.
    for packet in 0..packets {
        assert_eq!(
            buf[packet * 188],
            0x47,
            "TS sync byte missing at packet {packet} — the Node and Rust ciphers have diverged"
        );
    }
}
